### ISSUE TITLE
Np Int version

### ISSUE THREAD

**Issue by NitinAggarwal1** [Extreme-classification/ngame#3]
Saving model at: /home/jupyter/nitin_aggarwal/QCS/models/NGAME/STransformer/LF-QCS-LowesProducts-Leaf-3K/v_0_2/extreme/model_network.pkl
Traceback (most recent call last):
  File "/home/jupyter/nitin_aggarwal/QCS/ngame/ngame/run_scripts/../runner.py", line 240, in <module>
    run_ngame(
  File "/home/jupyter/nitin_aggarwal/QCS/ngame/ngame/run_scripts/../runner.py", line 209, in run_ngame
    ans = evaluate(
  File "/home/jupyter/nitin_aggarwal/QCS/ngame/ngame/run_scripts/../runner.py", line 66, in evaluate
    ans = func(
  File "/home/jupyter/nitin_aggarwal/QCS/ngame/ngame/tools/evaluate.py", line 89, in eval_with_score_fusion
    save_npz(fname, retain_topk(predictions, k=top_k),
  File "/home/jupyter/.local/lib/python3.10/site-packages/xclib-0.97-py3.10-linux-x86_64.egg/xclib/utils/sparse.py", line 137, in retain_topk
    ranks = rank(X)
  File "/home/jupyter/.local/lib/python3.10/site-packages/xclib-0.97-py3.10-linux-x86_64.egg/xclib/utils/sparse.py", line 36, in rank
    ranks = _rank(X.data, X.indices, X.indptr)
  File "xclib/utils/_sparse.pyx", line 197, in xclib.utils._sparse._rank
  File "/opt/conda/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.

I am not sure where the issue is coming .  I have changed the _sparse.pyx into int64 from int .

**Comment by NitinAggarwal1** [comment]
Issue was with pyxclib library . Its fixed by Anshul Mittal.
